### ISSUE TITLE
find example data for map

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/WetPaddlers#11]
find candidates for cool demo layers

**Comment by lunamoonmoon** [comment]
Idea: Education levels based on census areas
https://catalogue.data.gov.bc.ca/dataset/education-level-summaries-for-bc-census-subdivisions-2016-census
Can see differences in education levels b/w areas and examine potential barriers

**Comment by lunamoonmoon** [comment]
Idea: Where can I find salmon for a fishing trip weekend!
https://catalogue.data.gov.bc.ca/dataset/provincial-fish-ranges-generalized
Can see a large variety of fish species, filter for certain ones, and find some fishies nearby!

**Comment by lunamoonmoon** [comment]
Idea: Coal fields
https://catalogue.data.gov.bc.ca/dataset/coal-fields-of-bc-with-coal-bed-methane-potential
Can see that there are coals mines nearby, didn't realize that still happened here in BC (fun fact: Robert Dunsmir made his fortune off the coalmine up island and lived in craigdaroch castle!)

**Comment by lunamoonmoon** [comment]
Idea: Kids have Caribou Nightmeres
https://catalogue.data.gov.bc.ca/dataset/2b217585-f48d-4d9f-b7ba-746909ac35ca
https://catalogue.data.gov.bc.ca/dataset/95da1091-7e8c-4aa6-9c1b-5ab159ea7b42
Find out which school your kids should go to if they keep having nightmares of Caribou.

**Comment by lunamoonmoon** [comment]
Idea: Find areas of traditional Indigenous use
https://catalogue.data.gov.bc.ca/dataset/first-nation-traditional-use-study-sites-polygons
Cool to see areas that are traditionally significant to Indigenous peoples.
