### ISSUE TITLE
look up tippencanoe examples - try to create tileset

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/WetPaddlers#12]
look at mikes example in disc

**Comment by lunamoonmoon** [comment]
Mapbox tippencanoe
https://github.com/mapbox/tippecanoe

**Comment by dgboss** [comment]
Link to Mike's repo with helpful code: https://github.com/micheal-w-wells/WFSToPMTiles

**Comment by dgboss** [comment]
for OSX users who want to convert a geojson file to pmtiles format locally
```
brew install tippecanoe
tippecanoe -zg --projection=EPSG:4326 input.geojson --output=output.pmtiles --no-tile-compression
```
