### ISSUE TITLE
powerpoint

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/WetPaddlers#37]
thanks Luna for doing this : ) here's some notes to start with!  feel free to get input from rest of the gang and yourself of course : )

- [x] slide with pics of team members? 

- [x] why we are looking at new vector tile format
  * performance limitations of existing layers, some data sets very high on vertices
  * challenges in updating centrally stored layers for others, need for quick & dirty tile hosting
  * both WPS and Range in need of this - API component backlog item for both teams
  
- [x] what we made:
 * API GeoJSON -> ProtoMaps tile on s3
 * Map example for React + React-Leaflet + PMTile
 * Map example for React + Openlayers + PMTile? (WIP)
 * DataBC catalogue download uploader (WIP)
 * Shareable maps using above outputs?? (WIP)
 
- Things we could do in the future with this:
* DataBC WFS -> s3 tile link converter + CQl/SQL-like operations on features
* SLD to symbolizer converter (preseve existing stylesheets / automate this step)
* Attribution for imported layers
* Range will be using this tile format for offline maps!

**Comment by lunamoonmoon** [comment]
Link to powerpoint: https://bcgov-my.sharepoint.com/:p:/g/personal/luna_morris_gov_bc_ca/EeTkyhedFu5BhjgdmVPR4loBj6-lIy9NoQSPU_zl_I9n8g?e=bRjO1k
Currently in progress, demo at 3pm
